-- MySQL Script generated by MySQL Workbench
-- Wed May  1 20:48:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `PropertyID` INT NOT NULL,
  `PropertyName` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  PRIMARY KEY (`PropertyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `StaffID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Roles` VARCHAR(45) NULL,
  `PhoneNo` INT NULL,
  PRIMARY KEY (`StaffID`),
  CONSTRAINT `fk_Staff_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Hotel` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InventoryItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InventoryItem` (
  `ItemID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Quantity` INT NULL,
  `Threshold` FLOAT NULL,
  PRIMARY KEY (`ItemID`),
  CONSTRAINT `fk_InventoryItem_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Hotel` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `RoomID` INT NOT NULL,
  `RoomType` VARCHAR(45) NULL,
  `RoomNo` INT NULL,
  `Capacity` INT NULL,
  `No of Amenities` INT NULL,
  `Availabilty Status` VARCHAR(45) NULL,
  PRIMARY KEY (`RoomID`),
  CONSTRAINT `fk_Room_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Hotel` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Work_Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Work_Schedule` (
  `Schedule ID` INT NOT NULL,
  `Days of week` INT NULL,
  `Start_time` DATETIME NULL,
  `End_time` DATETIME NULL,
  `Year` VARCHAR(45) NULL,
  PRIMARY KEY (`Schedule ID`),
  CONSTRAINT `fk_Work_Schedule_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Staff` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payroll_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payroll_Data` (
  `Payroll_ID` INT NOT NULL,
  `Salary` FLOAT NULL,
  `Benefits` FLOAT NULL,
  `Deductions` VARCHAR(45) NULL,
  PRIMARY KEY (`Payroll_ID`),
  CONSTRAINT `fk_Payroll_Data_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Staff` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Performance_Evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Performance_Evaluation` (
  `Evaluation_ID` INT NOT NULL,
  `Evaluation_Date` DATE NULL,
  `Rating` FLOAT NULL,
  `Performance_Evaluationcol` VARCHAR(45) NULL,
  PRIMARY KEY (`Evaluation_ID`),
  CONSTRAINT `fk_Performance_Evaluation_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Staff` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guest` (
  `GuestID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `PhoneNo` INT NULL,
  `LPmembership` VARCHAR(45) NULL,
  `Notes` VARCHAR(255) NULL,
  PRIMARY KEY (`GuestID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guest_Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guest_Feedback` (
  `FeedbackID` INT NOT NULL,
  `Rating` FLOAT NULL,
  `Comments` VARCHAR(45) NULL,
  PRIMARY KEY (`FeedbackID`),
  CONSTRAINT `fk_Guest_Feedback_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Guest` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Preferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Preferences` (
  `Preferences_id` INT NOT NULL,
  `RoomType` VARCHAR(45) NULL,
  `FloorLevel` INT NULL,
  `Smoking_Non_Smoking` VARCHAR(45) NULL,
  PRIMARY KEY (`Preferences_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `ReservationID` INT NOT NULL,
  `CheckInDate` DATE NULL,
  `CheckOutDate` DATE NULL,
  PRIMARY KEY (`ReservationID`),
  CONSTRAINT `fk_Reservation_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Guest` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `Payment_ID` INT NOT NULL,
  `Payment_Method` VARCHAR(45) NULL,
  `Amount` FLOAT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`Payment_ID`),
  CONSTRAINT `fk_Payment_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Reservation` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `idServices` INT NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Price` VARCHAR(45) NULL,
  PRIMARY KEY (`idServices`),
  CONSTRAINT `fk_Services_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Staff` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Services_2`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Room` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
